spring:
    datasource:
        url: jdbc:mysql://localhost:3307/command
        username: root
        password: example
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true